FROM tomcat:9.0

ENV CATALINA_HOME=/usr/local/tomcat
ENV CATALINA_BASE=/usr/local/tomcat
ADD ./setenv.sh /usr/local/tomcat/bin

# Timezone
RUN mv /etc/localtime /etc/localtime_org \
    && ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

RUN rm -rf /usr/local/tomcat/webapps/*

COPY ./server.xml /usr/local/tomcat/conf/server.xml
COPY ./target/ROOT.war /usr/local/tomcat/webapps/.


ENTRYPOINT ["/usr/local/tomcat/bin/catalina.sh", "run"]

EXPOSE 8009

